### ISSUE TITLE
Keyboard Splitter worked for a few days 

### ISSUE THREAD

**Issue by pou556** [djlastnight/KeyboardSplitterXbox#11]
**It worked for a few days without any problem, but now it doenst open anymore, i got this**

[Mon] 17 Dec, 2018 [21:59:54] [Mem: 19 MB] - Application started from C:\Users\Paulo\Downloads\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 19 MB] - User has write permissions: True
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 19 MB] - OS version: Windows 10 x64 build 17134 
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 19 MB] - Setting environment
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 19 MB] - Extracting native resources
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
[Mon] 17 Dec, 2018 [21:59:54] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
[Mon] 17 Dec, 2018 [22:03:55] [Mem: 21 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Mon] 17 Dec, 2018 [22:03:55] [Mem: 21 MB] - System.Management.ManagementException: Invalid query 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Management.ManagementObjectCollection.get_Count()
   at Interceptor.InterceptionDriver.get_DriverState()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by djlastnight** [comment]
Preinstalling the built-in drivers should fix your issue.

**Comment by pou556** [comment]
I found a fix. Every time I have to open Keyboard Splitter I stop and start again the WMI service

**Comment by djlastnight** [comment]
Fine
