### ISSUE TITLE
Unexpected app crash occured.

### ISSUE THREAD

**Issue by DatorkasteLV** [djlastnight/KeyboardSplitterXbox#203]
Been trying to fix this for days but to no luck, KS opens a CMD for a second and then closes, after a second or two, error message pops up. KS used to work perfectly fine when I tried it almost a year ago on my PC, nothing has changed about my PC besides a new GPU and different monitors but I don't see how or why that would do anything, only real change i'd assume would be that I reinstalled my windows a month or two ago. KS never asked to install drivers either, I'd assume it crashes before it can do that? I've tried uninstalling interception drivers but to no luck, tried using Oblitum's uninstaller with CMD and the one provided here (Though looks like they're the same). Also tried uninstalling Scp virtual bus driver, I don't know if it was installed with KS or not, but I had it, uninstalled it, it never installed back again after opening KS.exe. Windows reinstallation would be the last last option I'd want to do because of how many things I'd have to backup and reinstall and I'd want to avoid that if possible. I also tried using earlier versions of KS but same thing happens, I'm lost.

Here are two logs from KS, one prior deleting interception drivers and one after. It doesn't seem to install them back either.
And only thing that has changed in the logs is the Interception driver state: not installed to installed.
[splitter_log.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/13998995/splitter_log.txt)
[splitter_log1.txt](https://github.com/djlastnight/KeyboardSplitterXbox/files/13998996/splitter_log1.txt)

[Thu] 29 Feb, 2024 [23:34:28] [Mem: 18 MB] - Application started from C:\Users\Ari\Desktop\KeyboardSplitter.exe
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 19 MB] - User has write permissions: True
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 19 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.3.0.0
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 19 MB] - OS version: Windows 10 x64 build 19045 
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 19 MB] - Setting environment
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 19 MB] - Loading interception 1.00
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 19 MB] - Loading VirtualXboxNative 2.2.0.0
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 25 MB] - Loading SplitterCore 2.2.0.0
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 25 MB] - Loading Interceptor 2.2.0.0
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 25 MB] - Loading VirtualXbox 2.2.0.0
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 26 MB] - Interception driver state: installed
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 26 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Thu] 29 Feb, 2024 [23:34:28] [Mem: 26 MB] - System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![crash](https://github.com/djlastnight/KeyboardSplitterXbox/assets/157241976/eeea6e14-3250-4f6a-9e5f-5b78a6405201)

**Comment by warof1820** [comment]
I have the same issue
EDIT: Actually I just also installed the Vcredist and now it starts up just fine. I also 'installed' the directX9 but I don't think I did that right because i had to manually select the file to extract it to and didn't know where so just put it in a place holder file. The video I watched someone install it only did the Xbox driver

**Comment by DatorkasteLV** [comment]
> I have the same issue EDIT: Actually I just also installed the Vcredist and now it starts up just fine. I also 'installed' the directX9 but I don't think I did that right because i had to manually select the file to extract it to and didn't know where so just put it in a place holder file. The video I watched someone install it only did the Xbox driver

I already have all prerequisites, tried reinstalling but nothing happened, thanks though.

**Comment by DatorkasteLV** [comment]
Any help would be appreciated
