### ISSUE TITLE
Keyboard splitter doesnt open

### ISSUE THREAD

**Issue by TarasNabaD** [djlastnight/KeyboardSplitterXbox#235]
![image](https://github.com/user-attachments/assets/b982aefe-cf81-4e6d-93a6-c16a8a4e7070)

Doesnt open, here are the logs

[Fri] 23 Aug, 2024 [22:30:49] [Mem: 17 MB] - Application started from C:\GaMe\Gayboard\KeyboardSplitter.exe
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 18 MB] - User has write permissions: True
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 18 MB] - OS version: Windows 10 x64 build 19045 
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 18 MB] - Setting environment
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 18 MB] - Loading interception 1.00
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 24 MB] - Loading VirtualXbox 2.2.0.0
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 25 MB] - Interception driver state: installed
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 25 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Fri] 23 Aug, 2024 [22:30:49] [Mem: 25 MB] - System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by TarasNabaD** [comment]
I have 2.2.0.0, but it has the same error on 2.3.0.0

**Comment by TarasNabaD** [comment]
well, i guess we will never know the solution(

**Comment by RayyanSheik** [comment]
DirectX 9.0c June
https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe

Vcredist 2013 x86
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe

Microsoft's Xbox Accessories Driver (64 bit)
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/Xbox360Accessories_x64_1.2.exe?raw=true


Download these. After I downloaded them it got fixed

**Comment by hquang-z** [comment]
i have same error , i download all them but the error don't fixed

**Comment by Jagu2812** [comment]
i have same error ,but after i downloaded all them but the error don't fixed
here are the logs 
[Mon] 07 Oct, 2024 [07:33:48] [Mem: 17 MB] - Application started from C:\Users\JAGAMOHAN\Downloads\Keyboard.Splitter.2.3.0.0\KeyboardSplitter.exe
[Mon] 07 Oct, 2024 [07:33:48] [Mem: 17 MB] - User has write permissions: True
[Mon] 07 Oct, 2024 [07:33:48] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.3.0.0
[Mon] 07 Oct, 2024 [07:33:48] [Mem: 17 MB] - OS version: Windows 10 x64 build 22631 
[Mon] 07 Oct, 2024 [07:33:48] [Mem: 17 MB] - Setting environment
[Mon] 07 Oct, 2024 [07:33:49] [Mem: 18 MB] - Loading interception 1.00
[Mon] 07 Oct, 2024 [07:33:49] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 07 Oct, 2024 [07:33:50] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Mon] 07 Oct, 2024 [07:33:50] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Mon] 07 Oct, 2024 [07:33:50] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 07 Oct, 2024 [07:33:50] [Mem: 20 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Mon] 07 Oct, 2024 [07:33:51] [Mem: 20 MB] - System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at Interceptor.InterceptionDriver.get_DriverState()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ihirwepatrick** [comment]
same error here
