### ISSUE TITLE
please help to use keyboard splitter

### ISSUE THREAD

**Issue by ghost** [djlastnight/KeyboardSplitterXbox#238]
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 18 MB] - User has write permissions: True
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 18 MB] - OS version: Windows 10 x64 build 22631 
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 18 MB] - Setting environment
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 18 MB] - Loading interception 1.00
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Tue] 08 Oct, 2024 [20:41:28] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Tue] 08 Oct, 2024 [20:41:29] [Mem: 21 MB] - Interception driver state: not installed
[Tue] 08 Oct, 2024 [20:41:29] [Mem: 21 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Tue] 08 Oct, 2024 [20:41:29] [Mem: 21 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by csha66** [comment]
Same problem, please help.

**Comment by ImSadist** [comment]
Same problem, none of the previous troubleshoots are working. I tried the solutions from #56, still no bueno please help.

**Comment by csha66** [comment]
Solved, should execute Visual C++ "vcredist_x86.exe" first

**Comment by pammcharm** [comment]
IT STILL NOT WORK AT ALL POSSIBLE FIX I TRY HARD AND HARD
