### ISSUE TITLE
umm, well... this is weird.

### ISSUE THREAD

**Issue by Ghostler55** [djlastnight/KeyboardSplitterXbox#240]
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 17 MB] - Application started from C:\Users\ghost\Downloads\Keyboard.Splitter.2.3.0.0\KeyboardSplitter.exe
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 17 MB] - User has write permissions: True
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.3.0.0
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 18 MB] - OS version: Windows 10 x64 build 19045 
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 18 MB] - Setting environment
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 18 MB] - Loading interception 1.00
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 24 MB] - Loading SplitterCore 2.2.0.0
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 24 MB] - Loading Interceptor 2.2.0.0
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 24 MB] - Loading VirtualXbox 2.2.0.0
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 21 MB] - Interception driver state: installed
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 21 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Sun] 13 Oct, 2024 [15:21:27] [Mem: 21 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Or I get this

[Sun] 13 Oct, 2024 [15:27:12] [Mem: 17 MB] - Application started from C:\Users\ghost\Downloads\Keyboard.Splitter.2.3.0.0\KeyboardSplitter.exe
[Sun] 13 Oct, 2024 [15:27:12] [Mem: 17 MB] - User has write permissions: True
[Sun] 13 Oct, 2024 [15:27:12] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.3.0.0
[Sun] 13 Oct, 2024 [15:27:12] [Mem: 18 MB] - OS version: Windows 10 x64 build 19045 
[Sun] 13 Oct, 2024 [15:27:12] [Mem: 18 MB] - Setting environment
[Sun] 13 Oct, 2024 [15:27:12] [Mem: 18 MB] - Loading interception 1.00
[Sun] 13 Oct, 2024 [15:27:12] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
卛湵⁝㌱传瑣‬〲㐲嬠㔱㈺㨷㈱⁝䵛浥›㐲䴠嵂ⴠ䰠慯楤杮匠汰瑩整䍲牯⁥⸲⸲⸰ര嬊匀甀渀崀 ㄀㌀ 伀挀琀Ⰰ ㈀　㈀㐀 嬀㄀㔀㨀㈀㜀㨀㄀㈀崀 嬀䴀攀洀㨀 ㈀㐀 䴀䈀崀 ⴀ 䰀漀愀搀椀渀最 匀瀀氀椀琀琀攀爀䌀漀爀攀 ㈀⸀㈀⸀　⸀　ഀ਀嬀畓嵮ㄠ″捏ⱴ㈠㈰‴ㅛ㨵㜲ㄺ崲嬠敍㩭㈠‴䉍⁝‭潌摡湩⁧湉整捲灥潴⁲⸲⸲⸰ര嬊匀甀渀崀 ㄀㌀ 伀挀琀Ⰰ ㈀　㈀㐀 嬀㄀㔀㨀㈀㜀㨀㄀㈀崀 嬀䴀攀洀㨀 ㈀㐀 䴀䈀崀 ⴀ 䰀漀愀搀椀渀最 䤀渀琀攀爀挀攀瀀琀漀爀 ㈀⸀㈀⸀　⸀　ഀ਀嬀匀甀渀崀 ㄀㌀ 伀挀琀Ⰰ ㈀　㈀㐀 嬀㄀㔀㨀㈀㜀㨀㄀㈀崀 嬀䴀攀洀㨀 ㈀㐀 䴀䈀崀 ⴀ 䰀漀愀搀椀渀最 嘀椀爀琀甀愀氀堀戀漀砀 ㈀⸀㈀⸀　⸀　ഀ਀嬀匀甀渀崀 ㄀㌀ 伀挀琀Ⰰ ㈀　㈀㐀 嬀㄀㔀㨀㈀㜀㨀㄀㈀崀 嬀䴀攀洀㨀 ㈀㈀ 䴀䈀崀 ⴀ 䤀渀琀攀爀挀攀瀀琀椀漀渀 搀爀椀瘀攀爀 猀琀愀琀攀㨀 椀渀猀琀愀氀氀攀搀ഀ਀嬀匀甀渀崀 ㄀㌀ 伀挀琀Ⰰ ㈀　㈀㐀 嬀㄀㔀㨀㈀㜀㨀㄀㈀崀 嬀䴀攀洀㨀 ㈀㈀ 䴀䈀崀 ⴀ 㨀㨀㨀 唀一䠀䄀一䐀䰀䔀䐀 䔀堀䌀䔀倀吀䤀伀一 䐀䔀吀䄀䤀䰀匀 㨀㨀㨀ഀ਀嬀匀甀渀崀 ㄀㌀ 伀挀琀Ⰰ ㈀　㈀㐀 嬀㄀㔀㨀㈀㜀㨀㄀㈀崀 嬀䴀攀洀㨀 ㈀㈀ 䴀䈀崀 ⴀ 匀礀猀琀攀洀⸀䐀氀氀一漀琀䘀漀甀渀搀䔀砀挀攀瀀琀椀漀渀㨀 唀渀愀戀氀攀 琀漀 氀漀愀搀 䐀䰀䰀 ✀嘀椀爀琀甀愀氀堀戀漀砀一愀琀椀瘀攀⸀搀氀氀✀㨀 吀栀攀 猀瀀攀挀椀昀椀攀搀 洀漀搀甀氀攀 挀漀甀氀搀 渀漀琀 戀攀 昀漀甀渀搀⸀ ⠀䔀砀挀攀瀀琀椀漀渀 昀爀漀洀 䠀刀䔀匀唀䰀吀㨀 　砀㠀　　㜀　　㜀䔀⤀ഀ਀   愀琀 嘀椀爀琀甀愀氀堀戀漀砀⸀一愀琀椀瘀攀䴀攀琀栀漀搀猀⸀嘀䈀甀猀䔀砀椀猀琀猀⠀⤀ഀ਀   愀琀 䬀攀礀戀漀愀爀搀匀瀀氀椀琀琀攀爀⸀䄀瀀瀀⸀刀攀瀀漀爀琀䐀爀椀瘀攀爀猀匀琀愀琀攀⠀⤀ഀ਀   愀琀 䬀攀礀戀漀愀爀搀匀瀀氀椀琀琀攀爀⸀䄀瀀瀀⸀䄀瀀瀀氀椀挀愀琀椀漀渀开匀琀愀爀琀甀瀀⠀伀戀樀攀挀琀 猀攀渀搀攀爀Ⰰ 匀琀愀爀琀甀瀀䔀瘀攀渀琀䄀爀最猀 攀⤀ഀ਀   愀琀 匀礀猀琀攀洀⸀圀椀渀搀漀眀猀⸀䄀瀀瀀氀椀挀愀琀椀漀渀⸀伀渀匀琀愀爀琀甀瀀⠀匀琀愀爀琀甀瀀䔀瘀攀渀琀䄀爀最猀 攀⤀ഀ਀   愀琀 匀礀猀琀攀洀⸀圀椀渀搀漀眀猀⸀䄀瀀瀀氀椀挀愀琀椀漀渀⸀㰀⸀挀琀漀爀㸀戀开开㄀开　⠀伀戀樀攀挀琀 甀渀甀猀攀搀⤀ഀ਀   愀琀 匀礀猀琀攀洀⸀圀椀渀搀漀眀猀⸀吀栀爀攀愀搀椀渀最⸀䔀砀挀攀瀀琀椀漀渀圀爀愀瀀瀀攀爀⸀䤀渀琀攀爀渀愀氀刀攀愀氀䌀愀氀氀⠀䐀攀氀攀最愀琀攀 挀愀氀氀戀愀挀欀Ⰰ 伀戀樀攀挀琀 愀爀最猀Ⰰ 䤀渀琀㌀㈀ 渀甀洀䄀爀最猀⤀ഀ਀   愀琀 匀礀猀琀攀洀⸀圀椀渀搀漀眀猀⸀吀栀爀攀愀搀椀渀最⸀䔀砀挀攀瀀琀椀漀渀圀爀愀瀀瀀攀爀⸀吀爀礀䌀愀琀挀栀圀栀攀渀⠀伀戀樀攀挀琀 猀漀甀爀挀攀Ⰰ 䐀攀氀攀最愀琀攀 挀愀氀氀戀愀挀欀Ⰰ 伀戀樀攀挀琀 愀爀最猀Ⰰ 䤀渀琀㌀㈀ 渀甀洀䄀爀最猀Ⰰ 䐀攀氀攀最愀琀攀 挀愀琀挀栀䠀愀渀搀氀攀爀⤀ഀ਀

**Comment by CartickKazama** [comment]
same is happening with me
