### ISSUE TITLE
Opened once but next time I started getting some error.Not opening now.Error log is below

### ISSUE THREAD

**Issue by ponrajeshkumar** [djlastnight/KeyboardSplitterXbox#5]
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 16 MB] - Application started from D:\Desktop\KS\KeyboardSplitter.exe
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 16 MB] - User has write permissions: True
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 16 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 16 MB] - OS version: Windows 10 x64 build 16299 
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 17 MB] - Setting environment
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 17 MB] - Extracting native resources
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 21 MB] - Loading SplitterCore 2.0.0.3
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 18 MB] - Loading Interceptor 2.0.0.3
[Tue] 06 Feb, 2018 [22:09:11] [Mem: 18 MB] - Loading VirtualXbox 2.0.0.3
[Tue] 06 Feb, 2018 [22:09:12] [Mem: 19 MB] - Interception driver state: installed
[Tue] 06 Feb, 2018 [22:09:12] [Mem: 19 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Tue] 06 Feb, 2018 [22:09:12] [Mem: 19 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by djlastnight** [comment]
You need vcredist 2013 x86. Probably that's the problem ;)

**Comment by ponrajeshkumar** [comment]
Cool.It worked.Thanks.Awesome software :)

**Comment by djlastnight** [comment]
I'm glad you like it :)
