### ISSUE TITLE
application crash

### ISSUE THREAD

**Issue by Shrubhi** [djlastnight/KeyboardSplitterXbox#51]
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 23 MB] - Application started from C:\Users\SHRUBHI\AppData\Local\Temp\Rar$EXa11392.34469\KeyboardSplitter.exe
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 23 MB] - User has write permissions: True
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 23 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 23 MB] - OS version: Windows 10 x64 build 19041 
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 23 MB] - Setting environment
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 23 MB] - Loading interception 1.00
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 23 MB] - Loading VirtualXboxNative 2.2.0.0
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 29 MB] - Loading SplitterCore 2.2.0.0
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 29 MB] - Loading Interceptor 2.2.0.0
[Mon] 27 Apr, 2020 [22:58:38] [Mem: 29 MB] - Loading VirtualXbox 2.2.0.0
[Mon] 27 Apr, 2020 [22:58:39] [Mem: 30 MB] - Interception driver state: not installed
[Mon] 27 Apr, 2020 [22:58:39] [Mem: 30 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Mon] 27 Apr, 2020 [22:58:39] [Mem: 30 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Krunal20** [comment]
I have exactly the same problem, please help

**Comment by RaKaa11** [comment]
i also have the same problem do you have any solution?

**Comment by RaKaa11** [comment]
@djlastnight keyboard splitter not working please help. it shows unexpected app crash occured

**Comment by RaKaa11** [comment]
[Fri] 08 May, 2020 [19:04:48] [Mem: 22 MB] - Application started from C:\Users\Welcome\Desktop\KeyboardSplitter.exe
[Fri] 08 May, 2020 [19:04:48] [Mem: 22 MB] - User has write permissions: True
[Fri] 08 May, 2020 [19:04:48] [Mem: 22 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Fri] 08 May, 2020 [19:04:48] [Mem: 22 MB] - OS version: Windows 10 x64 build 18362 
[Fri] 08 May, 2020 [19:04:48] [Mem: 22 MB] - Setting environment
[Fri] 08 May, 2020 [19:04:48] [Mem: 22 MB] - Extracting native resources
[Fri] 08 May, 2020 [19:04:48] [Mem: 32 MB] - Loading SplitterCore 2.0.0.3
[Fri] 08 May, 2020 [19:04:48] [Mem: 32 MB] - Loading Interceptor 2.0.0.3
[Fri] 08 May, 2020 [19:04:48] [Mem: 32 MB] - Loading VirtualXbox 2.0.0.3
[Fri] 08 May, 2020 [19:04:48] [Mem: 33 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Fri] 08 May, 2020 [19:04:48] [Mem: 34 MB] - System.Management.ManagementException: Invalid namespace 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at Interceptor.InterceptionDriver.get_DriverState()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RaKaa11** [comment]
@djlastnight 
![Screenshot (96)](https://user-images.githubusercontent.com/65025819/81410974-442de300-915f-11ea-87e7-94efc51eb4f3.png)

**Comment by Krunal20** [comment]
Hey guys, I got it working!
You just need to download vcredist 2013 x86 (repair if already installed), restart your PC and try again

**Comment by Krunal20** [comment]
Also make sure you have these:
dot NET Framework 4 (or newer)
DirectX 2010 June
No "Scp Virtual Bus Driver" installed (Check at Device Manager -> System Devices).
If you have it - uninstall it (check the 'Delete the driver software for this device' checkbox and reboot your PC.
No "Interception" driver installed.
If you are not sure - download command line tool from https://github.com/oblitum/Interception/releases/tag/1.0.0
Open cmd.exe as admin, navigate to install-interception.exe folder and type
install-interception /uninstall. Reboot your PC

**Comment by RaKaa11** [comment]
It didn't work!!

**Comment by Krunal20** [comment]
Sorry friend, this was all I knew

**Comment by RaKaa11** [comment]
Do u know any other application rather than keyboard splitter?

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
