### ISSUE TITLE
keyboard spiltter is not working

### ISSUE THREAD

**Issue by ghost** [djlastnight/KeyboardSplitterXbox#55]
[Tue] 12 May, 2020 [11:18:04] [Mem: 17 MB] - Application started from D:\Games\KeyboardSplitter.exe
[Tue] 12 May, 2020 [11:18:04] [Mem: 18 MB] - User has write permissions: True
[Tue] 12 May, 2020 [11:18:04] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.4
[Tue] 12 May, 2020 [11:18:04] [Mem: 18 MB] - OS version: Windows 10 x64 build 16299 
[Tue] 12 May, 2020 [11:18:04] [Mem: 18 MB] - Setting environment
[Tue] 12 May, 2020 [11:18:04] [Mem: 19 MB] - Extracting native resources
[Tue] 12 May, 2020 [11:18:04] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
[Tue] 12 May, 2020 [11:18:04] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
[Tue] 12 May, 2020 [11:18:04] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
[Tue] 12 May, 2020 [11:18:04] [Mem: 24 MB] - Interception driver state: not installed
[Tue] 12 May, 2020 [11:18:04] [Mem: 21 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Tue] 12 May, 2020 [11:18:04] [Mem: 21 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by djlastnight** [comment]
Yep https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
