### ISSUE TITLE
Keyboard Spilitter App Crash Error

### ISSUE THREAD

**Issue by sachinkcv** [djlastnight/KeyboardSplitterXbox#60]
System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Management.ManagementObjectCollection.get_Count()
   at Interceptor.InterceptionDriver.get_DriverState()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Log Generator

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
