### ISSUE TITLE
 cnbyf

### ISSUE THREAD

**Issue by ghost** [djlastnight/KeyboardSplitterXbox#72]
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 23 MB] - Application started from C:\Users\ROHAN'S PC\Downloads\docs\Files\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 23 MB] - User has write permissions: True
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 23 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 23 MB] - OS version: Windows 10 x64 build 18363 
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 23 MB] - Setting environment
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 23 MB] - Loading interception 1.00
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 23 MB] - Loading VirtualXboxNative 2.2.0.0
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 31 MB] - Loading SplitterCore 2.2.0.0
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 31 MB] - Loading Interceptor 2.2.0.0
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 32 MB] - Loading VirtualXbox 2.2.0.0
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 33 MB] - Interception driver state: installed
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 33 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Wed] 28 Oct, 2020 [14:39:28] [Mem: 33 MB] - System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
