### ISSUE TITLE
key board splitter not working

### ISSUE THREAD

**Issue by nafeesansa** [djlastnight/KeyboardSplitterXbox#80]
`[Fri] 25 Dec, 2020 [18:56:04] [Mem: 17 MB] - Application started from C:\Users\Nafees\Downloads\Files\Files\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Fri] 25 Dec, 2020 [18:56:04] [Mem: 17 MB] - User has write permissions: True
[Fri] 25 Dec, 2020 [18:56:04] [Mem: 17 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Fri] 25 Dec, 2020 [18:56:04] [Mem: 17 MB] - OS version: Windows 10 x64 build 16299 
[Fri] 25 Dec, 2020 [18:56:04] [Mem: 17 MB] - Setting environment
[Fri] 25 Dec, 2020 [18:56:04] [Mem: 17 MB] - Loading interception 1.00
[Fri] 25 Dec, 2020 [18:56:04] [Mem: 17 MB] - Loading VirtualXboxNative 2.2.0.0
[Fri] 25 Dec, 2020 [18:56:05] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Fri] 25 Dec, 2020 [18:56:05] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Fri] 25 Dec, 2020 [18:56:05] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Fri] 25 Dec, 2020 [18:56:05] [Mem: 20 MB] - Interception driver state: not installed
[Fri] 25 Dec, 2020 [18:56:05] [Mem: 20 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Fri] 25 Dec, 2020 [18:56:05] [Mem: 20 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`
the log is showing this and the splitter is not opening

**Comment by djlastnight** [comment]
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
