### ISSUE TITLE
keyboard splitter not working splitter log. attached

### ISSUE THREAD

**Issue by AK9954** [djlastnight/KeyboardSplitterXbox#98]
![image](https://user-images.githubusercontent.com/86184309/122667284-a618a300-d1cf-11eb-88ad-66cb2d654a87.png)
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 18 MB] - Application started from C:\Users\Anuraag\Downloads\Compressed\Keyboard.Splitter.2.0.0.3\KeyboardSplitter.exe
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 18 MB] - User has write permissions: True
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.0.0.3
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 18 MB] - OS version: Windows 7 x64 build 7601 Service Pack 1
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 18 MB] - Setting environment
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 18 MB] - Extracting native resources
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 24 MB] - Loading SplitterCore 2.0.0.3
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 24 MB] - Loading Interceptor 2.0.0.3
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 24 MB] - Loading VirtualXbox 2.0.0.3
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 25 MB] - Interception driver state: installed
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 25 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Sun] 20 Jun, 2021 [13:49:40] [Mem: 25 MB] - System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by djlastnight** [comment]
install this
https://github.com/djlastnight/KeyboardSplitterXbox/releases/latest
and this
https://github.com/djlastnight/KeyboardSplitterXbox#prerequisites
