### ISSUE TITLE
unexpected appcrash error

### ISSUE THREAD

**Issue by JcJit** [djlastnight/KeyboardSplitterXbox#99]
[Sun] 20 Jun, 2021 [12:54:00] [Mem: 18 MB] - Application started from C:\Users\Paul\Desktop\Keyboard splitter\KeyboardSplitter.exe
[Sun] 20 Jun, 2021 [12:54:00] [Mem: 18 MB] - User has write permissions: True
[Sun] 20 Jun, 2021 [12:54:00] [Mem: 18 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Sun] 20 Jun, 2021 [12:54:00] [Mem: 18 MB] - OS version: Windows 8.1 x64 build 9600 
[Sun] 20 Jun, 2021 [12:54:00] [Mem: 18 MB] - Setting environment
[Sun] 20 Jun, 2021 [12:54:00] [Mem: 18 MB] - Loading interception 1.00
[Sun] 20 Jun, 2021 [12:54:00] [Mem: 18 MB] - Loading VirtualXboxNative 2.2.0.0
[Sun] 20 Jun, 2021 [12:54:01] [Mem: 23 MB] - Loading SplitterCore 2.2.0.0
[Sun] 20 Jun, 2021 [12:54:01] [Mem: 23 MB] - Loading Interceptor 2.2.0.0
[Sun] 20 Jun, 2021 [12:54:01] [Mem: 23 MB] - Loading VirtualXbox 2.2.0.0
[Sun] 20 Jun, 2021 [12:54:01] [Mem: 24 MB] - Interception driver state: not installed
[Sun] 20 Jun, 2021 [12:54:01] [Mem: 24 MB] - ::: UNHANDLED EXCEPTION DETAILS :::
[Sun] 20 Jun, 2021 [12:54:01] [Mem: 24 MB] - System.DllNotFoundException: Unable to load DLL 'VirtualXboxNative.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at VirtualXbox.NativeMethods.VBusExists()
   at KeyboardSplitter.App.ReportDriversState()
   at KeyboardSplitter.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by JcJit** [comment]
someone Please help me out...I want to use multiple keyboards because I don't have game pads.

**Comment by djlastnight** [comment]
install those: https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/README.md#prerequisites
